name: YouTube Uploader

on:
  workflow_dispatch:
    inputs:
      video_path:
        description: 'Path to the video file'
        required: true
        default: 'video.mp4'
      title:
        description: 'Video Title'
        required: true
        default: 'My YouTube Video'
      description:
        description: 'Video Description'
        required: true
        default: 'Uploaded via GitHub Actions'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload to YouTube
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
        run: |
          python upload_to_youtube.py \
            --file "${{ github.event.inputs.video_path }}" \
            --title "${{ github.event.inputs.title }}" \
            --description "${{ github.event.inputs.description }}"
